name: one_cask
description: "Pixelfield Flutter Task"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # State management & Data models
  bloc: ^8.1.4 # State management
  flutter_bloc: ^8.1.6 # Widgets for easier bloc integration
  provider: ^6.1.2
  reactive_forms: ^17.0.1 # Simplifies form validation and data binding
  freezed_annotation: ^2.4.2 # Code generation for immutable classes
  json_annotation: ^4.9.0 # Code generation for JSON serialization
  shared_preferences: ^2.2.3
  connectivity_plus: ^6.0.3

  # Navigation
  go_router: ^14.2.0 # Most popular navigation library

  # UI
  google_fonts: ^6.2.1 # Simplifies using custom fonts
  animated_size_and_fade: ^4.0.0 # Used to animate sections in Bottle Detail

  # Splash & Icon
  flutter_native_splash: ^2.4.0 # Used to generate splash screen
  flutter_launcher_icons: ^0.13.1 # Used to generate app icons

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.11
  flutter_gen_runner:
  flutter_lints: ^3.0.0
  freezed: ^2.5.2
  json_serializable: ^6.8.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/data/
    - assets/img/
    - assets/img/icons/
